"""Daily summary generation — the copy-paste artifact for the real ELN.

Gathers a day's notebook entries (both app- and phone-sourced) plus the
experiments touched, and renders a clean dated report in Markdown and in plain
text. The user copies one of these straight into their enterprise ELN.
"""

from __future__ import annotations

from datetime import date, datetime
from typing import Optional

from .db import Connection
from .models import ENTRY_TYPE_LABELS
from .notebook import TS_FMT, list_entries

# Order entry types appear in the summary.
_SECTION_ORDER = ["task_done", "observation", "result", "deviation", "note"]
_SECTION_TITLES = {
    "task_done": "Tasks completed",
    "observation": "Observations",
    "result": "Results",
    "deviation": "Protocol deviations",
    "note": "Notes",
}


def _fmt_time(ts: str) -> str:
    try:
        return datetime.strptime(ts, TS_FMT).strftime("%H:%M")
    except ValueError:
        return ts


def build_daily_summary(conn: Connection, on_date: Optional[date] = None) -> dict[str, str]:
    """Return ``{"markdown": ..., "text": ...}`` for the given date (today by default)."""
    on_date = on_date or date.today()
    entries = list_entries(conn, on_date=on_date)
    # list_entries is newest-first; chronological reads better in a summary.
    entries = list(reversed(entries))

    experiments = sorted(
        {e["experiment_name"] for e in entries if e.get("experiment_name")}
    )

    md: list[str] = []
    txt: list[str] = []

    header = on_date.strftime("%A, %B %d, %Y")
    md.append(f"# Lab Notebook — {header}")
    txt.append(f"LAB NOTEBOOK — {header}")
    txt.append("=" * (len(txt[-1])))

    if experiments:
        md.append(f"\n**Experiments:** {', '.join(experiments)}")
        txt.append(f"\nExperiments: {', '.join(experiments)}")

    if not entries:
        md.append("\n_No entries recorded for this date._")
        txt.append("\nNo entries recorded for this date.")
        return {"markdown": "\n".join(md), "text": "\n".join(txt)}

    by_type: dict[str, list[dict]] = {}
    for e in entries:
        by_type.setdefault(e["entry_type"], []).append(e)

    for etype in _SECTION_ORDER:
        items = by_type.get(etype)
        if not items:
            continue
        title = _SECTION_TITLES.get(etype, ENTRY_TYPE_LABELS.get(etype, etype))
        md.append(f"\n## {title}")
        txt.append(f"\n{title.upper()}")
        for e in items:
            t = _fmt_time(e["created_at"])
            exp = f" [{e['experiment_name']}]" if e.get("experiment_name") else ""
            src = " (phone)" if e.get("source") == "phone" else ""
            body = e["text"].replace("\n", "\n    ")
            md.append(f"- **{t}**{exp}{src} — {body}")
            txt.append(f"  - {t}{exp}{src}: {body}")

    md.append(f"\n---\n_Generated by Seshat at {datetime.now().strftime('%Y-%m-%d %H:%M')}._")
    txt.append(f"\nGenerated by Seshat at {datetime.now().strftime('%Y-%m-%d %H:%M')}.")

    return {"markdown": "\n".join(md), "text": "\n".join(txt)}
