"""Daily summary generation — the copy-paste artifact for Labguru.

Gathers a day's notebook entries (both app- and phone-sourced), the experiments
active that day, and renders a clean dated report in three forms:
  * ``html``     — rich block to select-and-copy into Labguru's editor
  * ``markdown`` — for Markdown-aware targets / download
  * ``text``     — plain-text fallback
"""

from __future__ import annotations

import html as _html
from datetime import date, datetime
from typing import Optional

from . import experiments as exp_mod
from .db import Connection
from .models import ENTRY_TYPE_LABELS
from .notebook import TS_FMT, list_entries

# Order entry types appear in the summary.
_SECTION_ORDER = ["task_done", "observation", "result", "deviation", "note"]
_SECTION_TITLES = {
    "task_done": "Tasks completed",
    "observation": "Observations",
    "result": "Results",
    "deviation": "Protocol deviations",
    "note": "Notes",
}


def _fmt_time(ts: str) -> str:
    try:
        return datetime.strptime(ts, TS_FMT).strftime("%H:%M")
    except ValueError:
        return ts


def build_daily_summary(conn: Connection, on_date: Optional[date] = None) -> dict[str, str]:
    """Return ``{"html", "markdown", "text"}`` for the given date (today by default)."""
    on_date = on_date or date.today()
    entries = list_entries(conn, on_date=on_date)
    entries = list(reversed(entries))  # chronological reads better in a summary
    active = exp_mod.experiments_active_on(conn, on_date)

    md: list[str] = []
    txt: list[str] = []
    htm: list[str] = []

    header = on_date.strftime("%A, %B %d, %Y")
    md.append(f"# Lab Notebook — {header}")
    txt.append(f"LAB NOTEBOOK — {header}")
    txt.append("=" * len(txt[-1]))
    htm.append(f"<h1>Lab Notebook — {_html.escape(header)}</h1>")

    # ── Experiments active on this date ──────────────────────────────────────
    if active:
        md.append("\n## Active experiments")
        txt.append("\nACTIVE EXPERIMENTS")
        htm.append("<h2>Active experiments</h2><ul>")
        for e in active:
            label = e["name"]
            extras = []
            if e.get("type_name"):
                extras.append(e["type_name"])
            if e.get("end_date") and e.get("start_date"):
                extras.append(f"{e['start_date']}→{e['end_date']}")
            suffix = f" ({', '.join(extras)})" if extras else ""
            md.append(f"- **{label}**{suffix}")
            txt.append(f"  - {label}{suffix}")
            htm.append(f"<li><strong>{_html.escape(label)}</strong>{_html.escape(suffix)}</li>")
        htm.append("</ul>")

    if not entries:
        md.append("\n_No log entries recorded for this date._")
        txt.append("\nNo log entries recorded for this date.")
        htm.append("<p><em>No log entries recorded for this date.</em></p>")
        return {"html": "\n".join(htm), "markdown": "\n".join(md), "text": "\n".join(txt)}

    by_type: dict[str, list[dict]] = {}
    for e in entries:
        by_type.setdefault(e["entry_type"], []).append(e)

    for etype in _SECTION_ORDER:
        items = by_type.get(etype)
        if not items:
            continue
        title = _SECTION_TITLES.get(etype, ENTRY_TYPE_LABELS.get(etype, etype))
        md.append(f"\n## {title}")
        txt.append(f"\n{title.upper()}")
        htm.append(f"<h2>{_html.escape(title)}</h2><ul>")
        for e in items:
            t = _fmt_time(e["created_at"])
            exp = f" [{e['experiment_name']}]" if e.get("experiment_name") else ""
            src = " (phone)" if e.get("source") == "phone" else ""
            body = e["text"]
            md.append(f"- **{t}**{exp}{src} — {body.replace(chr(10), '; ')}")
            txt.append(f"  - {t}{exp}{src}: {body.replace(chr(10), '; ')}")
            htm.append(
                f"<li><strong>{t}</strong>{_html.escape(exp + src)} — "
                f"{_html.escape(body).replace(chr(10), '<br>')}</li>"
            )
        htm.append("</ul>")

    stamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    md.append(f"\n---\n_Generated by Seshat at {stamp}._")
    txt.append(f"\nGenerated by Seshat at {stamp}.")
    htm.append(f"<hr><p><em>Generated by Seshat at {stamp}.</em></p>")

    return {"html": "\n".join(htm), "markdown": "\n".join(md), "text": "\n".join(txt)}
